2021年 08月 23日 星期一 15:31:30 CST

diff --git a/stow_all b/stow_all
--- a/stow_all
+++ b/stow_all
@@ -29,7 +29,7 @@ function check_path() {
 }
 
 function install_home_dotfiles() {
-    HOME_DIR=$(find ./ -maxdepth 1 -type d -not -name ".*"|grep -v 'etc'|cut -d '/' -f 2|sort)
+    HOME_DIR=$(find ./ -maxdepth 1 -type d -not -name ".*"|grep -v 'etc'|grep -v 'usr'|cut -d '/' -f 2|sort)
     echo -e "\033[34m$HOME:install...\033[0m"
     for DOTFILES in $HOME_DIR
     do
@@ -61,8 +61,31 @@ function install_etc_dotfiles() {
     echo -e ""
 }
 
+function install_usr_dotfiles() {
+    USR_DIR=$(find ./usr/ -maxdepth 1 -type d |cut -d '/' -f 3|sed "1d")
+    echo -e "\033[34m/usr:install...\033[0m"
+
+    # plymouth depends on dejavu font
+    sudo mkdir -p /usr/share/fonts/truetype/dejavu
+    pushd usr > /dev/null
+    sudo $STOW $STOW_FLAG --target '/usr/share/fonts/truetype/dejavu' dejavu >/dev/null 2>&1
+    popd > /dev/null
+
+    if [ $? -eq 0 ] 
+    then
+        for DOTFILES in $USR_DIR
+        do
+            echo -e "$DOTFILES \033[32m stowed. \033[0m"
+        done
+    else
+        echo -e "\033[31m Error on stow usr. \033[0m"
+    fi
+    echo -e ""
+}
+
 check_root
 check_prog stow
 check_path
 install_home_dotfiles
 install_etc_dotfiles
+install_usr_dotfiles
diff --git a/unstow b/unstow
--- a/unstow
+++ b/unstow
@@ -49,31 +49,47 @@ function check_argv() {
 
 function unstow() {
 
-    HOME_DIR=$(find ./ -maxdepth 1 -type d -not -name ".*"|grep -v 'etc'|cut -d '/' -f 2|sort)
+    HOME_DIR=$(find ./ -maxdepth 1 -type d -not -name ".*"|grep -v 'etc'|grep -v 'usr'|cut -d '/' -f 2|sort)
     ETC_DIR=$(find ./etc/ -maxdepth 1 -type d |cut -d '/' -f 3|sed "1d")
+    USR_DIR=$(find ./usr/ -maxdepth 1 -type d |cut -d '/' -f 3|sed "1d")
 
     if [[ "$HOME_DIR" =~ "$1" ]]
     then
         $STOW $STOW_FLAG -D --target "$HOME" $1 >/dev/null 2>&1
         if [ $? -ne 0 ]
         then 
-        	echo -e "\033[31merror:\033[0m $1 is not in here."
-        exit 1
-	    fi
+            echo -e "\033[31merror:\033[0m $1 is not in here."
+            exit 1
+        fi
     elif [[ "$ETC_DIR" =~ "$1" ]]
     then
         pushd etc > /dev/null
         sudo $STOW $STOW_FLAG -D --target /etc/$1 $1 >/dev/null 2>&1
-	    if [ $? -ne 0 ]
+        if [ $? -ne 0 ]
         then 
-        	echo -e "\033[31merror:\033[0m $1 is not in here."
-        exit 1
-	    fi
+            echo -e "\033[31merror:\033[0m $1 is not in here."
+            exit 1
+        fi
         popd > /dev/null
+    elif [[ "$USR_DIR" =~ "$1" ]]
+    then
+        pushd usr > /dev/null
+
+        # plymouth depends on dejavu font
+        sudo $STOW $STOW_FLAG -D --target /usr/share/fonts/truetype/$1 $1 >/dev/null 2>&1
+        if [ $? -ne 0 ]
+        then 
+            echo -e "\033[31merror:\033[0m $1 is not in here."
+            exit 1
+        fi
+        sudo rmdir /usr/share/fonts/truetype/$1
+        popd > /dev/null
+
     else
         echo -e "\033[31merror:\033[0m $1 is not in here."
         exit 1
     fi
+
     echo -e "$1\033[33m unstowed.\033[0m"
 }
 
diff --git a/unstow_all b/unstow_all
--- a/unstow_all
+++ b/unstow_all
@@ -1,8 +1,6 @@
 #!/usr/bin/env bash
 # uninstall my dotfiles.
 
-HOME_DIR=$(find ./ -maxdepth 1 -type d -not -name ".*"|grep -v 'etc'|cut -d '/' -f 2|sort)
-ETC_DIR=$(find ./etc/ -maxdepth 1 -type d |cut -d '/' -f 3|sed "1d")
 STOW="/usr/bin/stow"
 PWD=$(basename $(pwd))
 STOW_FLAG="--no-fold --restow"
@@ -31,6 +29,7 @@ function check_path() {
 }
 
 function uninstall_home_dotfiles() {
+    HOME_DIR=$(find ./ -maxdepth 1 -type d -not -name ".*"|grep -v 'etc'|cut -d '/' -f 2|sort)
     echo -e "\033[34m$HOME:uninstall...\033[0m"
     for DOTFILES in $HOME_DIR
     do
@@ -47,6 +46,7 @@ function uninstall_home_dotfiles() {
 }
 
 function uninstall_etc_dotfiles() {
+    ETC_DIR=$(find ./etc/ -maxdepth 1 -type d |cut -d '/' -f 3|sed "1d")
     echo -e "\033[34m/etc:uninstall...\033[0m"
     sudo $STOW $STOW_FLAG -D --target "/etc" etc 2> /dev/null
     if [ $? -eq 0 ] 
@@ -61,11 +61,31 @@ function uninstall_etc_dotfiles() {
     echo -e ""
 }
 
+function uninstall_usr_dotfiles() {
+    USR_DIR=$(find ./usr/ -maxdepth 1 -type d |cut -d '/' -f 3|sed "1d")
+    echo -e "\033[34m/usr:uninstall...\033[0m"
 
-    
+    # plymouth depends on dejavu font
+    pushd usr > /dev/null
+    sudo $STOW $STOW_FLAG -D --target /usr/share/fonts/truetype/dejavu dejavu >/dev/null 2>&1
+    popd > /dev/null
+
+    if [ $? -eq 0 ] 
+    then
+        for DOTFILES in $USR_DIR
+        do
+            echo -e "$DOTFILES \033[33m has been deleted. \033[0m"
+        done
+    else
+        echo -e "\033[31m Error on delete usr. \033[0m"
+    fi
+    sudo rmdir /usr/share/fonts/truetype/dejavu
+    echo -e ""
+}
 
 check_root
 check_prog stow
 check_path
 uninstall_home_dotfiles
 uninstall_etc_dotfiles
+uninstall_usr_dotfiles
